include /etc/nginx/include/upstream.inc;

server {
   listen	80;
   
   
   server_name	example-http.com;
   

   access_log	/var/log/nginx/example-http.com-acess.log;
   error_log	/var/log/nginx/example-http.com-error.log;

   root /var/www/img;

   location / {
                proxy_pass      http://localhost:1325;

   }   


   location ~* \.(jpg|jpeg)$ {
                access_log off;
                expires 30d;
   }


}
